Using btn-primary in order to pass SkyA11y tests
blackbaud/skyux-template pull request #42
Opened 2017-10-12 16:49 UTC by Blackbaud-BobbyEarl

2017-10-13 14:09 UTC, Blackbaud-RoseWhipple approved these changes

2017-10-13 16:24 UTC, Blackbaud-RoseWhipple requested changes
use-btn-primary is the correct branch, right? I cloned this repo, checked out the branch, and then ran `npm install` and `skyux e2e`. It's still producing the same error as before.

2017-10-13 19:19 UTC, Blackbaud-BobbyEarl commented
Yep, that's the right branch.  That's weird, I've done that exact thing a couple times and see the test as always passing.

2017-10-13 21:23 UTC, Blackbaud-RoseWhipple approved these changes
Ok, I found out what was going on. For some reason even though git said I had checked out `use-btn-primary`, when I went to go look at the changed file locally, the changes weren't there. Guessing it might be a permissions thing because I'm not allowed to pull. I made the change manually and the tests now pass.

2017-10-16 15:27 UTC, Blackbaud-SteveBrush approved these changes

2017-10-16 15:27 UTC, merged